### PR TITLE
Fix #1001

### LINKED ISSUE #1001: Assertion failed on mutual recursion with optional arguments
Minimal example and triggered assertion:
```ocaml
type t = int option

let rec f ?(optional : t) () = f ?optional ()
and g () = f ?optional:(Some 1) ()
```
```
> dune build @doc
odoc: internal error, uncaught exception:
      File "src/loader/cmi.ml", line 420, characters 21-27: Assertion failed
      Raised at Odoc_loader__Cmi.read_type_expr in file "src/loader/cmi.ml", line 420, characters 21-33
      Called from Odoc_loader__Cmt.read_pattern in file "src/loader/cmt.ml", line 40, characters 22-57
      Called from Odoc_loader__Cmt.read_value_bindings.(fun) in file "src/loader/cmt.ml", line 92, characters 18-50
      Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
      Called from Odoc_loader__Cmt.read_value_bindings in file "src/loader/cmt.ml", line 86, characters 4-360
      Called from Odoc_loader__Cmt.read_structure.(fun) in file "src/loader/cmt.ml", line 583, characters 24-61
      Called from Stdlib__List.fold_left in file "list.ml", line 121, characters 24-34
      Called from Odoc_loader__Cmt.read_structure in file "src/loader/cmt.ml", line 581, characters 4-127
      Called from Odoc_loader__Cmt.read_implementation in file "src/loader/cmt.ml", line 596, characters 4-74
      Called from Odoc_loader.read_cmt in file "src/loader/odoc_loader.ml", line 145, characters 34-74
      Called from Odoc_loader.wrap_errors.(fun) in file "src/loader/odoc_loader.ml", line 164, characters 10-14
      Called from Odoc_model__Error.catch in file "src/model/error.ml", line 54, characters 21-27
      Called from Odoc_model__Error.catch_warnings.(fun) in file "src/model/error.ml", line 89, characters 18-22
      Called from Odoc_model__Error.with_ref in file "src/model/error.ml", line 67, characters 12-16
      Re-raised at Odoc_model__Error.with_ref in file "src/model/error.ml", line 72, characters 4-11
      Called from Odoc_odoc__Compile.resolve_and_substitute in file "src/odoc/compile.ml", line 87, characters 4-31
      Called from Odoc_model__Error.catch in file "src/model/error.ml", line 54, characters 21-27
      Called from Odoc_model__Error.catch_warnings.(fun) in file "src/model/error.ml", line 89, characters 18-22
      Called from Odoc_model__Error.with_ref in file "src/model/error.ml", line 67, characters 12-16
      Re-raised at Odoc_model__Error.with_ref in file "src/model/error.ml", line 72, characters 4-11
      Called from Odoc_odoc__Compile.compile.(fun) in file "src/odoc/compile.ml", line 239, characters 6-136
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 24, characters 19-24
      Called from Cmdliner_term.app.(fun) in file "cmdliner_term.ml", line 22, characters 12-19
      Called from Cmdliner_eval.run_parser in file "cmdliner_eval.ml", line 34, characters 37-44
```
```
> dune --version
3.10.0
> odoc --version
2.2.1
```
Type annotations avoid hitting the assertion:
```ocaml
type t = int option

let rec f ?(optional : t) () = (f : ?optional:int -> unit -> unit) ?optional ()
and g () = (f : ?optional:int -> unit -> unit) ?optional:(Some 1) ()
```

### PR DESCRIPTION
**Pull request by jonludlam**
This is a very simplistic fix, and will only truly fix the simple cases. The less-simple cases will now show an error in the generated docs as opposed to catastrophically failing.

### CODE REVIEW

File: src/document/generator.ml [hunk 1]
```diff
@@ -26,6 +26,8 @@ let tag tag t = O.span ~attr:tag t
 let label t =
   match t with
   | Odoc_model.Lang.TypeExpr.Label s -> tag "label" (O.txt s)
+  | RawOptional _s ->
+      tag "error" (O.txt "Error: RawOptional found during rendering")
```
Comment (Julow) [inline src/document/generator.ml:30]: That renders badly:


Readers of the doc can't do anything about that and we have the tag available. Why not print it the same as `Optional` ? Perhaps using the `tag "error"` but leaving the correct rendering.

File: test/xref2/github_issue_1001.t/run.t [hunk 2]
```diff
@@ -0,0 +1,28 @@
+  $ ocamlc -c -bin-annot test.ml
+  $ odoc compile test.cmt
+  $ odoc link test.odoc
+  $ odoc html-generate -o html test.odocl
+  $ odoc support-files -o html
+
+We should have an 'Optional' argument (as opposed to a 'RawOptional' one)
+
+  $ odoc_print -r f test.odocl
```
Comment (Julow) [inline test/xref2/github_issue_1001.t/run.t:9]: I think it could be useful to have the problematic case as well. I added it here: https://github.com/jonludlam/odoc/pull/48

File: src/document/generator.ml (hunk 1 above)
Comment (jonludlam) [reply src/document/generator.ml:30]: Hmm, yes, I think we can do better here.

File: test/xref2/github_issue_1001.t/run.t (hunk 2 above)
Comment (jonludlam) [reply test/xref2/github_issue_1001.t/run.t:9]: thanks!

File: src/document/generator.ml (hunk 1 above)
Comment (Julow) [reply src/document/generator.ml]: Now renders like this:

**Review by Julow — APPROVED** [review]
Let's merge!
